server:
  port: 8081
spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my2?useSSL=true&serverTimezone=Asia/Shanghai

mybatis:
  type-aliases-package: com.example.springboot.pojo
